export const resources = {
  en: {
    translation: {
      nav: { home: "Home", feed: "Feed", playlist: "Playlist", settings: "Settings", player: "Now Playing" },
      common: { error: "Error", cancel: "Cancel", remove: "Remove", delete: "Delete", retry: "Retry", play: "Play", pause: "Pause", loading: "Loading…", unknown: "Unknown", untitled: "Untitled", done: "Done" },
      home: { title: "Convert Audio", pasteUrl: "Paste YouTube URL", paste: "Paste", convert: "Convert", cacheFailed: "Caching failed", retryCache: "Retry caching", conversionFailed: "Conversion failed", failedAt: "Failed during {{phase}}", expired: "Audio has expired. Please submit the URL again.", progress: { queued: "Queued", download: "Download", transcode: "Transcode", save: "Save", playable: "Playable" } },
      progress: { playable: "Playable", cachingToDevice: "Caching to your device in the background", cached: "Cached", availableOffline: "Available offline", cacheFailedStreaming: "Caching failed; streaming is still available", retrying: "Retrying", retryingDetail: "The previous attempt failed; retrying automatically", queued: "Queued", queuedDetail: "Waiting for the conversion service", preparing: "Preparing conversion", preparingDetail: "Preparing audio conversion", downloading: "Downloading", downloadingDetail: "Getting audio from YouTube", transcoding: "Transcoding", transcodingDetail: "Converting to a playable format", saving: "Saving", savingDetail: "Saving the audio file", processing: "Processing", ready: "Completed" },
      feed: { noSubscriptions: "No Subscriptions", addToBrowse: "Add a YouTube channel to start browsing.", addChannel: "Add Channel", manageChannels: "Manage Channels", all: "All", loading: "Loading feed…", loadFailed: "Failed to load feed. Pull down to retry.", noVideos: "No videos found", removeTitle: "Remove Channel", removeMessage: "Remove this channel from your subscriptions?", convert: "Convert", cacheFailed: "Caching failed", caching: "Caching", ago: { minute_one: "{{count}}m ago", minute_other: "{{count}}m ago", hour_one: "{{count}}h ago", hour_other: "{{count}}h ago", day_one: "{{count}}d ago", day_other: "{{count}}d ago" } },
      channel: { title: "Add Channel", placeholder: "YouTube channel URL or @handle", helper: "Paste a YouTube channel link or @handle to follow its latest videos.", add: "Add", confirm: "Follow channel", close: "Close", preview: "Channel preview", added: "Channel added" },
      playlist: { title: "My Music", edit: "Edit", selectAll: "Select all", clearAll: "Clear all", selected: "{{count}} selected", selectTracks: "Select tracks", empty: "No tracks yet. Convert a YouTube URL to get started.", deleteTrackTitle: "Delete Track", deleteTrackMessage: "Remove \"{{title}}\" from your library? The audio file will also be deleted.", deleteTracksTitle: "Delete tracks", deleteTracksMessage: "Remove {{count}} selected tracks? The audio files will also be deleted.", deleteSelected: "Delete ({{count}})", listened: "listened" },
      player: { noTrack: "No track playing", loading: "Loading audio…", caching: "Caching", cached: "Cached", cacheFailed: "Caching failed", streaming: "Streaming", notCached: "Not cached", retryCache: "Retry caching", expired: "Audio has expired. Please convert it again.", failed: "Playback failed. Please try again.", previous: "Previous track", next: "Next track", seek: "Playback position", openSource: "Open video source" },
      settings: { title: "Settings", language: "Language", system: "Follow system", chinese: "简体中文", english: "English", checkStorage: "Check Storage", storage: "{{count}} tracks, {{size}}", about: "About", description: "TubeCast — your personal YouTube audio library", source: "Source code" },
      errors: { generic: "Something went wrong. Please try again.", network: "Network request failed. Please try again." },
    },
  },
  "zh-CN": {
    translation: {
      nav: { home: "首页", feed: "订阅", playlist: "播放列表", settings: "设置", player: "正在播放" },
      common: { error: "错误", cancel: "取消", remove: "移除", delete: "删除", retry: "重试", play: "播放", pause: "暂停", loading: "加载中…", unknown: "未知", untitled: "未命名", done: "完成" },
      home: { title: "转换音频", pasteUrl: "粘贴 YouTube 链接", paste: "粘贴", convert: "转换", cacheFailed: "缓存失败", retryCache: "重试缓存", conversionFailed: "转换失败", failedAt: "失败发生在{{phase}}阶段", expired: "音频已过期，请重新提交链接。", progress: { queued: "排队", download: "下载", transcode: "转码", save: "保存", playable: "可播放" } },
      progress: { playable: "可播放", cachingToDevice: "正在后台缓存到手机", cached: "已缓存", availableOffline: "可离线播放", cacheFailedStreaming: "缓存失败，仍可在线播放", retrying: "重试中", retryingDetail: "上次尝试失败，正在自动重试", queued: "排队中", queuedDetail: "等待转换服务接收任务", preparing: "准备转换", preparingDetail: "正在准备音频转换", downloading: "下载中", downloadingDetail: "正在从 YouTube 获取音频", transcoding: "转码中", transcodingDetail: "正在转换为可播放格式", saving: "保存中", savingDetail: "正在保存音频文件", processing: "处理中", ready: "已完成" },
      feed: { noSubscriptions: "还没有订阅", addToBrowse: "添加 YouTube 频道以浏览最新内容。", addChannel: "添加频道", manageChannels: "管理频道", all: "全部", loading: "正在加载订阅内容…", loadFailed: "加载订阅内容失败，请下拉重试。", noVideos: "没有找到视频", removeTitle: "移除频道", removeMessage: "要从订阅中移除此频道吗？", convert: "转换", cacheFailed: "缓存失败", caching: "缓存中", ago: { minute_one: "{{count}} 分钟前", minute_other: "{{count}} 分钟前", hour_one: "{{count}} 小时前", hour_other: "{{count}} 小时前", day_one: "{{count}} 天前", day_other: "{{count}} 天前" } },
      channel: { title: "添加频道", placeholder: "YouTube 频道链接或 @handle", helper: "粘贴 YouTube 频道链接或 @handle，即可订阅最新视频。", add: "添加", confirm: "订阅频道", close: "关闭", preview: "频道预览", added: "已添加频道" },
      playlist: { title: "我的音乐", edit: "编辑", selectAll: "全选", clearAll: "取消全选", selected: "已选 {{count}} 项", selectTracks: "选择曲目", empty: "还没有曲目。转换一个 YouTube 链接即可开始。", deleteTrackTitle: "删除曲目", deleteTrackMessage: "要从音乐库移除“{{title}}”吗？音频文件也会被删除。", deleteTracksTitle: "删除曲目", deleteTracksMessage: "要移除选中的 {{count}} 首曲目吗？音频文件也会被删除。", deleteSelected: "删除 ({{count}})", listened: "已收听" },
      player: { noTrack: "当前没有播放曲目", loading: "正在加载音频…", caching: "缓存中", cached: "已缓存", cacheFailed: "缓存失败", streaming: "在线播放", notCached: "未缓存", retryCache: "重试缓存", expired: "音频已过期，请重新转换。", failed: "播放失败，请重试。", previous: "上一首", next: "下一首", seek: "播放位置", openSource: "打开视频来源" },
      settings: { title: "设置", language: "语言", system: "跟随系统", chinese: "简体中文", english: "English", checkStorage: "查看存储空间", storage: "{{count}} 首曲目，{{size}}", about: "关于", description: "TubeCast — 你的个人 YouTube 音频库", source: "源代码" },
      errors: { generic: "操作失败，请重试。", network: "网络请求失败，请重试。" },
    },
  },
} as const;
