export type JobStatus = "queued" | "processing" | "ready" | "failed";
export type SummaryStatus = "idle" | "processing" | "ready" | "failed";

export type Job = {
  id: string;
  sourceUrl: string;
  sourceKey: string | null;
  sourceId: string | null;
  title: string | null;
  channelName: string | null;
  channelId: string | null;
  thumbnailUrl: string | null;
  durationSeconds: number | null;
  status: JobStatus;
  summaryStatus: SummaryStatus;
  summaryText: string | null;
  summaryErrorMessage: string | null;
  summaryUpdatedAt: string | null;
  idempotencyKey: string | null;
  requestedDeviceIdHash?: string | null;
  audioPath: string | null;
  audioHref: string | null;
  audioUrl: string | null;
  audioExpiresAt?: string | null;
  audioDeletedAt?: string | null;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
  filename: string | null;
};
